### ISSUE TITLE
make_build_wheels.py fails

### ISSUE THREAD

**Issue by boisgera** [ziglang/zig-pypi#13]
Hi folks!

Thanks for this project, I find the idea of installing zig via pip awesome! ❤️

I'd like to understand how this works under the hood. But so far I didn't manage to build the wheels:

```console
$ python make_wheels.py 
142caa3b804d86b4752556c9b6b039b7517a08afa3af842645c7e2dcd125f652 https://ziglang.org/download/0.11.0/zig-windows-x86_64-0.11.0.zip
Traceback (most recent call last):
...
ValueError: ZipInfo required
```

Full error message here: https://github.com/boisgera/zig-pypi/actions/runs/5837365956/job/15832774824

My platform is Ubuntu with Python 3.11.

Does this error ring a bell for anyone?

Best Regards,

Sébastien

**Comment by whitequark** [comment]
Try Python 3.10. Does that work?

**Comment by boisgera** [comment]
No, I have the same issue with Python 3.10 (see https://github.com/boisgera/zig-pypi/actions/runs/5837527994/job/15833190226).

**Comment by whitequark** [comment]
That's interesting. I'll take a look.

**Comment by boisgera** [comment]
AFAICT, the build works with Python 3.10 AND wheel 0.38 (but not wheel 0.40).

**Comment by boisgera** [comment]
> AFAICT, the build works with Python 3.10 AND wheel 0.38 (but not wheel 0.40).

See https://github.com/boisgera/zig-pypi/actions/runs/5840512680

**Comment by whitequark** [comment]
All right. I'll add a lockfile to avoid this in the future, and investigate the issue as well.
