### ISSUE TITLE
Support armv7l architecture 

### ISSUE THREAD

**Issue by MikeKlem** [ziglang/zig-pypi#3]
Can you publish a wheel for armv7l?

Older RasPi’s, various embedded boards, OpenWRT routers are the things that could be supported, in addition to the aarch64 port already present

**Comment by whitequark** [comment]
Yep.

**Comment by whitequark** [comment]
Done: https://files.pythonhosted.org/packages/91/b5/25f833c31f53edee8a51a9a47f93db84699393b8613decd2c2c6378f5f4f/ziglang-0.8.0-py3-none-manylinux_2_17_armv7l.manylinux2014_armv7l.whl
