### ISSUE TITLE
Use os.exec rather than sys.exit(subprocess.call(...))

### ISSUE THREAD

**Issue by adamchainz** [ziglang/zig-pypi#6]
Using an `os.exec*` function, when available (Unix, Windows) will replace the Python wrapper process, rather than keeping it around until zig has finished. This saves memory and makes processes easier to debug.

You should be able to change:

```python
sys.exit(subprocess.call([
    os.path.join(os.path.dirname(__file__), "{entry_name}"),
    *sys.argv[1:]
]))
```

to something like:

```python
path = os.path.join(os.path.dirname(__file__), "{entry_name}")
os.execvp("zig", path, *sys.argv[1:])
```

**Comment by adamchainz** [comment]
Oh interesting, good to know. Perhaps there could be a check to use `exec` on unix only?

**Comment by whitequark** [comment]
There could be, but I'm worried about issues that arise from using different mechanisms on Unix and Windows. (This is why it doesn't already use `os.exec`.)

**Comment by andrewrk** [comment]
For what it's worth, the zig binary itself will use execve on Unix for `zig run` and CreateProcessW on Windows.

**Comment by whitequark** [comment]
Does it wait for the process to terminate?

**Comment by andrewrk** [comment]
The CreateProcessW path? Yes, I believe this would be equivalent to the status quo python code.

**Comment by whitequark** [comment]
No objection to using `os.execvp` on Unix then.
